export const skill = [
  { title: "react" },
  { title: "javascript" },
  { title: "jest" },
  { title: "redux" },
  { title: "tailwind" },
  { title: "node" },
  { title: "react native" },
  { title: "expo" },
  { title: "typescript" },
  { title: "css" },
  { title: "html" },
  { title: "next" },
  { title: "bootstrap" },
  { title: "babel" },
  { title: "mongodb" },
  { title: "firebase" },
  { title: "postgreSQL" },
  { title: "git" },
];
