import Head from "next/head";
import { Header } from "../components/Header";
import { Inter } from "@next/font/google";
import Hero from "../components/Hero";
import { About } from "../components/About";
import { Experience } from "../components/Experience";
import { Skills } from "../components/Skills";
import { Projects } from "../components/Projects";
import { Contact } from "../components/Contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-primary-color/80 z-0">
      <Head>
        <title>Cristobal's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section id="hero" className="snap-start">
        <Hero />
      </section>

      <section id="About" className="snap-center">
        <About />
      </section>

      {/*  <section id="Experience" className="snap-center">
        <Experience />
      </section>
 */}
      <section id="Skills" className="snap-start">
        <Skills />
      </section>

      <section id="Projects" className="snap-start">
        <Projects />
      </section>

      <section id="Contact" className="snap-start">
        <Contact />
      </section>
    </div>
  );
}
